"""
Reporting Synthesizer — generates a professional forensic report from worker findings.

Uses Gemini to produce a C-suite-ready executive summary alongside the full
technical detail, all mapped to MITRE ATT&CK.  The LLM only summarises and
structures — it cannot introduce new evidence beyond what the workers found.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List

from case_brief import CASE_NAME, INCIDENT_SUMMARY, INVESTIGATION_DIRECTIVES
from models import Finding


_SYNTH_PROMPT = """You are a senior forensic report writer. Given the structured findings below from four independent investigation agents, produce a professional forensic report.

CASE: {case_name}
INCIDENT: {incident_summary}

FINDINGS FROM INVESTIGATION AGENTS:
{findings_json}

DATABASE STATISTICS:
{db_stats}

REPORT REQUIREMENTS:
1. Executive Summary (2-3 paragraphs for C-suite): What happened, how bad is it, what to do next. No technical jargon.
2. For each finding (A, B, C, D):
   - Title with MITRE ATT&CK technique IDs
   - Confidence level and status
   - Narrative summary explaining the evidence chain
   - Key evidence items with specific IPs, timestamps, and numbers
   - Limitations and gaps
3. Attack Timeline: Chronological sequence of events
4. Recommendations: Prioritized remediation steps

RULES:
- Do NOT invent any data not present in the findings above.
- Use specific numbers, IPs, and timestamps from the evidence items.
- Be honest about confidence levels and limitations.
- Balance technical depth with executive accessibility.

Return the report as a complete Markdown document.
"""


def synthesize_report(
    findings: Dict[str, Finding],
    db_stats: dict,
    model: str = "",
) -> str:
    """
    Generate a professional Markdown forensic report from worker findings.

    Falls back to a template-based report if Gemini is unavailable.
    """
    model = model or os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

    findings_data = {}
    for qid, finding in findings.items():
        directive = INVESTIGATION_DIRECTIVES.get(qid, {})
        findings_data[qid] = {
            "title": finding.title,
            "question": directive.get("question", ""),
            "status": finding.status,
            "confidence": finding.confidence,
            "mitre": finding.mitre,
            "summary": finding.summary,
            "evidence": [e.to_dict() for e in finding.evidence],
            "limitations": finding.limitations,
            "next_steps": finding.next_steps,
        }

    prompt = _SYNTH_PROMPT.format(
        case_name=CASE_NAME,
        incident_summary=INCIDENT_SUMMARY,
        findings_json=json.dumps(findings_data, indent=2),
        db_stats=json.dumps(db_stats, indent=2),
    )

    backend = os.getenv("LLM_BACKEND", "gemini").strip().lower()

    try:
        if backend == "deepseek":
            # DeepSeek / OpenAI-compatible backend
            api_key = os.getenv("DEEPSEEK_API_KEY", "").strip()
            if not api_key:
                raise RuntimeError("No DeepSeek API key")
            base_url = os.getenv("DEEPSEEK_BASE_URL", "https://api.deepseek.com")
            ds_model = os.getenv("DEEPSEEK_MODEL", "deepseek-chat")
            from openai import OpenAI
            client = OpenAI(api_key=api_key, base_url=base_url)
            response = client.chat.completions.create(
                model=ds_model,
                messages=[
                    {"role": "system", "content": "You are a senior forensic report writer."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
            )
            return response.choices[0].message.content or _template_report(findings, db_stats)
        else:
            # Gemini backend
            api_key = os.getenv("GEMINI_API_KEY", "").strip() or os.getenv("GOOGLE_API_KEY", "").strip()
            if not api_key:
                raise RuntimeError("No API key")
            from google import genai
            from google.genai import types
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model=model,
                contents=prompt,
                config=types.GenerateContentConfig(temperature=0.3),
            )
            return response.text or _template_report(findings, db_stats)
    except Exception as e:
        # Fallback to template-based report
        return _template_report(findings, db_stats)


def _template_report(findings: Dict[str, Finding], db_stats: dict) -> str:
    """Template-based fallback report when LLM is unavailable."""
    lines = []
    lines.append(f"# Agentic Network Forensic Report — {CASE_NAME}")
    lines.append(f"\n*Generated by Multi-Agent Forensic Engine*\n")

    lines.append("## Executive Summary\n")
    lines.append(
        "This report was generated by an orchestrated multi-agent forensic system. "
        "Four specialized AI agents independently investigated Initial Access, Lateral Movement, "
        "Exfiltration, and Payload Deployment, using SQL queries against a structured evidence database. "
        "Every finding is grounded in data from Suricata alerts, Zeek logs, and deep PCAP analysis.\n"
    )
    lines.append(INCIDENT_SUMMARY + "\n")

    lines.append("## Evidence Database\n")
    lines.append("| Table | Rows |")
    lines.append("|-------|------|")
    for table, count in sorted(db_stats.get("table_counts", db_stats).items()):
        lines.append(f"| {table} | {count:,} |")
    lines.append("")

    for qid in ["A", "B", "C", "D"]:
        finding = findings.get(qid)
        directive = INVESTIGATION_DIRECTIVES[qid]
        lines.append(f"## {qid}. {directive['title']}")
        lines.append(f"**MITRE ATT&CK:** {', '.join(directive['primary_mitre'])}\n")

        if not finding:
            lines.append("*No finding recorded.*\n")
            continue

        lines.append(f"**Status:** {finding.status} | **Confidence:** {finding.confidence}\n")
        lines.append(finding.summary + "\n")

        if finding.evidence:
            lines.append("### Evidence\n")
            for i, item in enumerate(finding.evidence, 1):
                lines.append(f"**{i}.** [{item.artifact}]")
                if item.ts:
                    lines.append(f"  - Timestamp: `{item.ts}`")
                if item.src_ip or item.dst_ip:
                    lines.append(f"  - Flow: `{item.src_ip}` → `{item.dst_ip}` ({item.protocol})")
                lines.append(f"  - {item.description}\n")

        if finding.limitations:
            lines.append("### Limitations\n")
            for lim in finding.limitations:
                lines.append(f"- {lim}")
            lines.append("")

        if finding.next_steps:
            lines.append("### Recommended Next Steps\n")
            for step in finding.next_steps:
                lines.append(f"- {step}")
            lines.append("")

    lines.append("## Methodology\n")
    lines.append(
        "This investigation was conducted by a multi-agent AI system consisting of:\n"
        "1. **Data Reduction Pipeline** — Suricata alerts, Zeek JSON, and PCAPs parsed into a structured SQLite database\n"
        "2. **Orchestrated Worker Agents** — Four Gemini-powered agents independently investigated each forensic question\n"
        "3. **Deterministic Tool-Calling Guardrails** — Agents could ONLY access evidence via SQL queries; hallucination was structurally prevented\n"
        "4. **Reporting Synthesizer** — Findings aggregated into this MITRE ATT&CK-mapped report\n"
    )

    return "\n".join(lines)
