"""
Reporting Synthesizer — generates a professional forensic report from worker findings.

Uses Gemini to produce a C-suite-ready executive summary alongside the full
technical detail, all mapped to MITRE ATT&CK.  The LLM only summarises and
structures — it cannot introduce new evidence beyond what the workers found.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List

from case_brief import CASE_NAME, INCIDENT_SUMMARY, INVESTIGATION_DIRECTIVES
from models import Finding


_SYNTH_PROMPT = """You are a senior forensic report writer. Given the structured findings below from four independent investigation agents, produce a professional forensic report.

CASE: {case_name}
INCIDENT: {incident_summary}

FINDINGS FROM INVESTIGATION AGENTS:
{findings_json}

DATABASE STATISTICS:
{db_stats}

REPORT REQUIREMENTS:
1. Executive Summary (2-3 paragraphs for C-suite): What happened, how bad is it, what to do next. No technical jargon.
2. For each finding (A, B, C, D):
   - Title with MITRE ATT&CK technique IDs
   - Confidence level and status
   - Narrative summary explaining the evidence chain
   - Key evidence items with specific IPs, timestamps, and numbers
   - Limitations and gaps
3. Attack Timeline: Chronological sequence of events
4. Recommendations: Prioritized remediation steps

RULES:
- Do NOT invent any data not present in the findings above.
- Use specific numbers, IPs, and timestamps from the evidence items.
- Be honest about confidence levels and limitations.
- Balance technical depth with executive accessibility.

Return the report as a complete Markdown document.
"""


def synthesize_report(
    findings: Dict[str, Finding],
    db_stats: dict,
    model: str = "",
) -> str:
    """
    Generate a professional Markdown forensic report from worker findings using GPT-4o.
    """
    model = model or os.getenv("OPENAI_MODEL", "gpt-4o")
    api_key = os.getenv("OPENAI_API_KEY", "").strip()

    if not api_key:
        print("  [Synthesizer] OPENAI_API_KEY missing, using template report")
        return _template_report(findings, db_stats)

    findings_data = {}
    for qid, finding in findings.items():
        directive = INVESTIGATION_DIRECTIVES.get(qid, {})
        # Safety: truncate evidence if there's too much for the prompt
        evidence_list = [e.to_dict() for e in finding.evidence]
        if len(evidence_list) > 15:
            evidence_list = evidence_list[:15]
            evidence_list.append({"note": "... truly large amount of evidence; truncated for reporting."})

        findings_data[qid] = {
            "title": finding.title,
            "question": directive.get("question", ""),
            "status": finding.status,
            "confidence": finding.confidence,
            "mitre": finding.mitre,
            "summary": finding.summary,
            "evidence": evidence_list,
            "limitations": finding.limitations,
            "next_steps": finding.next_steps,
        }

    prompt = _SYNTH_PROMPT.format(
        case_name=CASE_NAME,
        incident_summary=INCIDENT_SUMMARY,
        findings_json=json.dumps(findings_data, indent=2),
        db_stats=json.dumps(db_stats, indent=2),
    )

    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are a senior forensic report writer."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
        )
        result = response.choices[0].message.content
        if result:
            print(f"  [Synthesizer] Report generated using openai/{model}")
            return result
    except Exception as e:
        print(f"  [Synthesizer] openai/{model} failed: {str(e)[:100]}")

    print("  [Synthesizer] All LLM backends failed, using template report")
    return _template_report(findings, db_stats)


def _template_report(findings: Dict[str, Finding], db_stats: dict) -> str:
    """Template-based fallback report when LLM is unavailable."""
    lines = []
    lines.append(f"# Agentic Network Forensic Report — {CASE_NAME}")
    lines.append(f"\n*Generated by Multi-Agent Forensic Engine*\n")

    lines.append("## Executive Summary\n")
    lines.append(
        "This report was generated by an orchestrated multi-agent forensic system. "
        "Four specialized AI agents independently investigated Initial Access, Lateral Movement, "
        "Exfiltration, and Payload Deployment, using SQL queries against a structured evidence database. "
        "Every finding is grounded in data from Suricata alerts, Zeek logs, and deep PCAP analysis.\n"
    )
    lines.append(INCIDENT_SUMMARY + "\n")

    lines.append("## Evidence Database\n")
    lines.append("| Table | Rows |")
    lines.append("|-------|------|")
    for table, count in sorted(db_stats.get("table_counts", db_stats).items()):
        lines.append(f"| {table} | {count:,} |")
    lines.append("")

    for qid in ["A", "B", "C", "D"]:
        finding = findings.get(qid)
        directive = INVESTIGATION_DIRECTIVES[qid]
        lines.append(f"## {qid}. {directive['title']}")
        lines.append(f"**MITRE ATT&CK:** {', '.join(directive['primary_mitre'])}\n")

        if not finding:
            lines.append("*No finding recorded.*\n")
            continue

        lines.append(f"**Status:** {finding.status} | **Confidence:** {finding.confidence}\n")
        lines.append(finding.summary + "\n")

        if finding.evidence:
            lines.append("### Evidence\n")
            for i, item in enumerate(finding.evidence, 1):
                lines.append(f"**{i}.** [{item.artifact}]")
                if item.ts:
                    lines.append(f"  - Timestamp: `{item.ts}`")
                if item.src_ip or item.dst_ip:
                    lines.append(f"  - Flow: `{item.src_ip}` → `{item.dst_ip}` ({item.protocol})")
                lines.append(f"  - {item.description}\n")

        if finding.limitations:
            lines.append("### Limitations\n")
            for lim in finding.limitations:
                lines.append(f"- {lim}")
            lines.append("")

        if finding.next_steps:
            lines.append("### Recommended Next Steps\n")
            for step in finding.next_steps:
                lines.append(f"- {step}")
            lines.append("")

    lines.append("## Methodology\n")
    lines.append(
        "This investigation was conducted by a multi-agent AI system consisting of:\n"
        "1. **Data Reduction Pipeline** — Suricata alerts, Zeek JSON, and PCAPs parsed into a structured SQLite database\n"
        "2. **Orchestrated Worker Agents** — Four Gemini-powered agents independently investigated each forensic question\n"
        "3. **Deterministic Tool-Calling Guardrails** — Agents could ONLY access evidence via SQL queries; hallucination was structurally prevented\n"
        "4. **Reporting Synthesizer** — Findings aggregated into this MITRE ATT&CK-mapped report\n"
    )

    return "\n".join(lines)
