from __future__ import annotations

import json
from pathlib import Path
from typing import List

from case_brief import CASE_NAME, INCIDENT_SUMMARY, INVESTIGATION_DIRECTIVES
from models import AnalysisState


def _format_list(items: List[str]) -> str:
    if not items:
        return "- None recorded"
    return "\n".join(f"- {item}" for item in items)


def write_outputs(state: AnalysisState) -> None:
    output_dir = Path(state.work_dir)

    # findings.json
    findings_path = output_dir / "findings.json"
    findings_path.write_text(
        json.dumps({key: value.to_dict() for key, value in state.findings.items()}, indent=2),
        encoding="utf-8",
    )

    # agent_log.json
    agent_log_path = output_dir / "agent_log.json"
    agent_log_path.write_text(json.dumps(state.agent_log, indent=2), encoding="utf-8")

    # report.md
    lines: List[str] = []
    lines.append(f"# Agentic Network Forensic Report – {CASE_NAME}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append(
        "This report was generated by a constrained forensic agent that uses alert-driven "
        "evidence extraction and a bounded reasoning loop. "
        "Its findings should be reviewed by a human analyst before external distribution."
    )
    lines.append("")

    lines.append("## Scope and Assumptions")
    lines.append(INCIDENT_SUMMARY)
    lines.append("")

    # ── Ingest statistics ─────────────────────────────────────────────────────
    a = state.artifacts
    lines.append("## Evidence Sources")
    lines.append(f"- Alert JSON: `{a.get('alert_json_path', 'N/A')}`")
    lines.append(f"- Zeek JSON:  `{a.get('zeek_json_path', 'N/A')}`")
    lines.append(f"- PCAP dir:   `{a.get('pcap_dir', 'N/A')}`")
    lines.append("")
    lines.append("### Ingest Statistics")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Suricata alerts | {a.get('alert_total', 0):,} |")

    alert_cats = a.get("alert_categories", {})
    for cat, cnt in sorted(alert_cats.items(), key=lambda x: -x[1]):
        if cnt > 0:
            lines.append(f"| Alerts – {cat} | {cnt:,} |")

    lines.append(f"| Zeek lines scanned | {a.get('zeek_scanned', 0):,} |")
    lines.append(f"| Zeek records matched | {a.get('zeek_matched', 0):,} |")
    lines.append(f"| Total PCAPs indexed | {a.get('pcap_count', 0)} |")
    lines.append(f"| Targeted PCAPs opened | {len(a.get('targeted_pcaps', []))} |")
    lines.append(f"| DNS queries extracted | {len(a.get('pcap_dns_queries', []))} |")
    lines.append(f"| TLS sessions extracted | {len(a.get('pcap_tls_sessions', []))} |")
    lines.append(f"| HTTP requests extracted | {len(a.get('pcap_http_requests', []))} |")
    lines.append(f"| SMB sessions extracted | {len(a.get('pcap_smb_sessions', []))} |")
    lines.append(f"| RDP sessions extracted | {len(a.get('pcap_rdp_sessions', []))} |")
    lines.append("")

    top_rules = a.get("alert_top_rules", [])
    if top_rules:
        lines.append("### Top Alert Rules")
        lines.append("| Rule | Count |")
        lines.append("|------|-------|")
        for rule in top_rules[:10]:
            name = rule.get("name", "")[:80]
            lines.append(f"| {name} | {rule.get('count', 0)} |")
        lines.append("")

    targeted = a.get("targeted_pcaps", [])
    if targeted:
        lines.append("### Targeted PCAP Files")
        for p in targeted[:20]:
            lines.append(f"- `{Path(p).name}`")
        if len(targeted) > 20:
            lines.append(f"- … plus {len(targeted) - 20} more")
        lines.append("")

    # ── Findings ──────────────────────────────────────────────────────────────
    lines.append("## Findings")
    for key in ["A", "B", "C", "D"]:
        finding = state.findings.get(key)
        directive = INVESTIGATION_DIRECTIVES[key]
        lines.append(f"### {key}. {directive['title']}")
        if not finding:
            lines.append("No finding recorded.")
            lines.append("")
            continue
        lines.append(f"**Status:** {finding.status}")
        lines.append(f"**Confidence:** {finding.confidence}")
        lines.append(f"**MITRE:** {', '.join(finding.mitre) if finding.mitre else 'Not mapped'}")
        lines.append("")
        lines.append(finding.summary)
        lines.append("")
        lines.append("**Evidence:**")
        if finding.evidence:
            for item in finding.evidence:
                lines.append(
                    f"- `{item.ts or 'ts?'}` | {item.protocol} | "
                    f"`{item.src_ip}` → `{item.dst_ip}` | {item.description} "
                    f"| _Artifact: {item.artifact}_"
                )
        else:
            lines.append("- No evidence items recorded")
        lines.append("")
        lines.append("**Limitations:**")
        lines.append(_format_list(finding.limitations))
        lines.append("")
        lines.append("**Recommended next steps:**")
        lines.append(_format_list(finding.next_steps))
        lines.append("")

    # ── Timeline ──────────────────────────────────────────────────────────────
    lines.append("## Timeline")
    timeline_path = output_dir / "timeline.json"
    if timeline_path.exists():
        timeline = json.loads(timeline_path.read_text(encoding="utf-8"))
        if timeline:
            for event in timeline:
                lines.append(
                    f"- `{event['ts'] or 'ts?'}` | {event['title']} | "
                    f"`{event['src_ip']}` → `{event['dst_ip']}` | {event['summary']}"
                )
        else:
            lines.append("- Timeline is empty")
    else:
        lines.append("- Timeline was not generated")
    lines.append("")

    # ── Guardrails ────────────────────────────────────────────────────────────
    lines.append("## Methodology and Guardrails")
    lines.append(
        "The agent follows a four-phase alert-driven pipeline: "
        "(1) Suricata alert ingestion, "
        "(2) Zeek JSON correlation filtered to IOC IPs, "
        "(3) targeted PCAP selection by timestamp, "
        "(4) deep tshark analysis on selected PCAPs only."
    )
    lines.append("")
    lines.append("- Read-only PCAP handling")
    lines.append("- Fixed tool allowlist (initial_access, lateral_movement, exfiltration, payload_delivery)")
    lines.append("- Evidence-linked conclusions – every finding cites actual log entries")
    lines.append("- Confidence labels (HIGH/MEDIUM/LOW) with explicit limitations")
    lines.append("- Safe abstention when evidence is weak")
    lines.append("- Results cached in `ingest/` to avoid re-scanning the 30 GB Zeek file")
    lines.append("")
    lines.append("## Cost and Efficiency Notes")
    lines.append(
        "- The Zeek JSON is streamed once and matched records are cached; re-runs are fast.\n"
        "- tshark is invoked only on the targeted PCAP subset, not all 129 files.\n"
        "- Deterministic mode has zero model cost; LLM mode adds cost only for planning.\n"
        "- This keeps the expensive reasoning layer narrow and auditable."
    )

    report_path = output_dir / "report.md"
    report_path.write_text("\n".join(lines), encoding="utf-8")
