from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Optional

from case_brief import CASE_NAME, INCIDENT_SUMMARY, INVESTIGATION_DIRECTIVES
from models import AnalysisState, Finding


def _format_list(items: List[str]) -> str:
    if not items:
        return "- None recorded"
    return "\n".join(f"- {item}" for item in items)


def _bytes_human(b) -> str:
    """Convert bytes to human-readable string."""
    try:
        b = int(b)
    except (TypeError, ValueError):
        return str(b)
    if b >= 1_073_741_824:
        return f"{b:,} bytes ({b / 1_073_741_824:.2f} GB)"
    elif b >= 1_048_576:
        return f"{b:,} bytes ({b / 1_048_576:.0f} MB)"
    elif b >= 1024:
        return f"{b:,} bytes ({b / 1024:.0f} KB)"
    return f"{b:,} bytes"


def write_outputs(state: AnalysisState) -> None:
    output_dir = Path(state.work_dir)

    # findings.json
    findings_path = output_dir / "findings.json"
    findings_path.write_text(
        json.dumps({key: value.to_dict() for key, value in state.findings.items()}, indent=2),
        encoding="utf-8",
    )

    # agent_log.json
    agent_log_path = output_dir / "agent_log.json"
    agent_log_path.write_text(json.dumps(state.agent_log, indent=2), encoding="utf-8")

    # report.md — comprehensive forensic report (always written, overwrites any
    # prior LLM-synthesized report since the template version includes timeline,
    # IOC table, MITRE mapping, and recommendations that the LLM version may lack)
    report_md = _build_detailed_report(state, output_dir)
    report_path = output_dir / "report.md"
    report_path.write_text(report_md, encoding="utf-8")


def _build_detailed_report(state: AnalysisState, output_dir: Path) -> str:
    """Build a comprehensive, detailed forensic report from all available data."""
    lines: List[str] = []
    a = state.artifacts

    # ═══════════════════════════════════════════════════════════════════════════
    # TITLE AND EXECUTIVE SUMMARY
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append(f"# Agentic Network Forensic Report – {CASE_NAME}")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(
        "This report was generated by an autonomous multi-agent forensic investigation system. "
        "Four specialized AI agents independently investigated distinct phases of the attack "
        "lifecycle — Initial Access, Lateral Movement & Discovery, Data Exfiltration, and "
        "Payload Deployment — using SQL queries against a structured evidence database. "
        "Every finding is grounded in data from Suricata IDS alerts, Zeek network logs, "
        "and deep PCAP analysis. No endpoint telemetry was available; all conclusions are "
        "derived exclusively from network evidence."
    )
    lines.append("")
    lines.append(
        "**This report should be reviewed by a human analyst before external distribution.** "
        "The autonomous agents operate under strict guardrails (read-only SQL, bounded iterations, "
        "evidence-linked claims), but their conclusions represent algorithmic analysis, not expert judgment."
    )
    lines.append("")

    # Executive finding summary
    lines.append("### Key Findings at a Glance")
    lines.append("")
    lines.append("| Phase | Finding | Confidence | Status |")
    lines.append("|-------|---------|------------|--------|")
    for key in ["A", "B", "C", "D"]:
        finding = state.findings.get(key)
        directive = INVESTIGATION_DIRECTIVES[key]
        if finding:
            # Extract first sentence of summary
            first_sentence = finding.summary.split(". ")[0] + "."
            if len(first_sentence) > 120:
                first_sentence = first_sentence[:117] + "..."
            lines.append(f"| {key}. {directive['title']} | {first_sentence} | {finding.confidence} | {finding.status} |")
        else:
            lines.append(f"| {key}. {directive['title']} | No finding recorded | — | — |")
    lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # SCOPE AND ASSUMPTIONS
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## Scope and Assumptions")
    lines.append("")
    lines.append(INCIDENT_SUMMARY)
    lines.append("")
    lines.append(
        "**Limitations of network-only analysis:** Without endpoint telemetry (EDR logs, "
        "memory dumps, disk images), certain activities are invisible to this investigation — "
        "including local command execution, process creation, file encryption operations, "
        "and interactive RDP session content. Conclusions about payload execution and "
        "impact are necessarily inferential."
    )
    lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # EVIDENCE SOURCES AND INGEST STATISTICS
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## Evidence Sources")
    lines.append("")
    lines.append(f"- **Alert JSON:** `{a.get('alert_json_path', 'N/A')}`")
    lines.append(f"- **Zeek JSON:** `{a.get('zeek_json_path', 'N/A')}`")
    lines.append(f"- **PCAP directory:** `{a.get('pcap_dir', 'N/A')}`")
    lines.append("")

    lines.append("### Ingest Statistics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total Suricata alerts | {a.get('alert_total', 0):,} |")

    alert_cats = a.get("alert_categories", {})
    for cat, cnt in sorted(alert_cats.items(), key=lambda x: -x[1]):
        if cnt > 0:
            lines.append(f"| Alerts – {cat} | {cnt:,} |")

    lines.append(f"| Zeek lines scanned | {a.get('zeek_scanned', 0):,} |")
    lines.append(f"| Zeek records matched | {a.get('zeek_matched', 0):,} |")
    lines.append(f"| Total PCAPs indexed | {a.get('pcap_count', 0)} |")
    lines.append(f"| Targeted PCAPs opened | {len(a.get('targeted_pcaps', []))} |")
    lines.append(f"| DNS queries extracted | {len(a.get('pcap_dns_queries', []))} |")
    lines.append(f"| TLS sessions extracted | {len(a.get('pcap_tls_sessions', []))} |")
    lines.append(f"| HTTP requests extracted | {len(a.get('pcap_http_requests', []))} |")
    lines.append(f"| SMB sessions extracted | {len(a.get('pcap_smb_sessions', []))} |")
    lines.append(f"| RDP sessions extracted | {len(a.get('pcap_rdp_sessions', []))} |")
    lines.append(f"| TCP conversations extracted | {len(a.get('pcap_tcp_conversations', []))} |")
    lines.append("")

    top_rules = a.get("alert_top_rules", [])
    if top_rules:
        lines.append("### Top Alert Rules")
        lines.append("")
        lines.append("| Rule | Count |")
        lines.append("|------|-------|")
        for rule in top_rules[:10]:
            name = rule.get("name", "")[:80]
            lines.append(f"| {name} | {rule.get('count', 0):,} |")
        lines.append("")

    targeted = a.get("targeted_pcaps", [])
    if targeted:
        lines.append("### Targeted PCAP Files")
        lines.append("")
        for p in targeted[:20]:
            lines.append(f"- `{Path(p).name}`")
        if len(targeted) > 20:
            lines.append(f"- … plus {len(targeted) - 20} more")
        lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # DETAILED FINDINGS
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## Findings")
    lines.append("")

    for key in ["A", "B", "C", "D"]:
        finding = state.findings.get(key)
        directive = INVESTIGATION_DIRECTIVES[key]
        mitre_ids = ", ".join(directive.get("primary_mitre", []))

        lines.append(f"### {key}. {directive['title']}")
        lines.append(f"**MITRE ATT&CK:** {mitre_ids}")
        lines.append("")

        if not finding:
            lines.append("*No finding recorded for this phase.*")
            lines.append("")
            continue

        lines.append(f"**Status:** {finding.status} | **Confidence:** {finding.confidence}")
        lines.append("")

        # Investigation question
        question = directive.get("question", "")
        if question:
            lines.append(f"> **Investigation Question:** {question}")
            lines.append("")

        # Full narrative summary
        lines.append("#### Summary")
        lines.append("")
        lines.append(finding.summary)
        lines.append("")

        # Evidence table
        if finding.evidence:
            lines.append("#### Evidence")
            lines.append("")
            lines.append("| # | Timestamp | Source → Destination | Protocol | Description | Data Source |")
            lines.append("|---|-----------|---------------------|----------|-------------|-------------|")
            for i, item in enumerate(finding.evidence, 1):
                ts = f"`{item.ts}`" if item.ts else "—"
                flow = f"`{item.src_ip}` → `{item.dst_ip}`" if (item.src_ip or item.dst_ip) else "—"
                proto = item.protocol or "—"
                desc = item.description.replace("|", "∣").replace("\n", " ")
                if len(desc) > 200:
                    desc = desc[:197] + "..."
                artifact = item.artifact or "—"
                lines.append(f"| {i} | {ts} | {flow} | {proto} | {desc} | {artifact} |")
            lines.append("")

        # Limitations
        if finding.limitations:
            lines.append("#### Limitations")
            lines.append("")
            for lim in finding.limitations:
                lines.append(f"- {lim}")
            lines.append("")

        # Recommended next steps
        if finding.next_steps:
            lines.append("#### Recommended Next Steps")
            lines.append("")
            for step in finding.next_steps:
                lines.append(f"- {step}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # IOC SUMMARY TABLE
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## Indicators of Compromise (IOC)")
    lines.append("")
    ioc_rows = _extract_iocs(state.findings)
    if ioc_rows:
        lines.append("| Type | Value | Context | Phase | First Seen |")
        lines.append("|------|-------|---------|-------|------------|")
        for ioc in ioc_rows:
            lines.append(f"| {ioc['type']} | `{ioc['value']}` | {ioc['context']} | {ioc['phase']} | {ioc.get('first_seen', '—')} |")
        lines.append("")
    else:
        lines.append("*No IOCs extracted from findings.*")
        lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # ATTACK TIMELINE
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## Attack Timeline")
    lines.append("")
    timeline_path = output_dir / "timeline.json"
    if timeline_path.exists():
        timeline = json.loads(timeline_path.read_text(encoding="utf-8"))
        if timeline:
            lines.append("| # | Timestamp | Phase | Source → Destination | Description |")
            lines.append("|---|-----------|-------|---------------------|-------------|")
            for i, event in enumerate(timeline, 1):
                ts = f"`{event.get('ts', '—')}`"
                title = event.get("title", "—")
                src = event.get("src_ip", "—")
                dst = event.get("dst_ip", "—")
                summary = event.get("summary", "").replace("|", "∣").replace("\n", " ")
                if len(summary) > 200:
                    summary = summary[:197] + "..."
                lines.append(f"| {i} | {ts} | {title} | `{src}` → `{dst}` | {summary} |")
            lines.append("")
        else:
            lines.append("*Timeline is empty.*")
            lines.append("")
    else:
        lines.append("*Timeline was not generated.*")
        lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # MITRE ATT&CK MAPPING
    # ═══════════════════════════════════════════════════════════════════════════
    lines.append("## MITRE ATT&CK Mapping")
    lines.append("")
    lines.append("| Tactic | Technique ID | Technique Name | Evidence Summary |")
    lines.append("|--------|-------------|----------------|-----------------|")

    mitre_map = {
        "T1133": ("Initial Access", "External Remote Services"),
        "T1078": ("Initial Access", "Valid Accounts"),
        "T1078.002": ("Initial Access", "Valid Accounts: Domain Accounts"),
        "T1046": ("Discovery", "Network Service Discovery"),
        "T1018": ("Discovery", "Remote System Discovery"),
        "T1087.002": ("Discovery", "Domain Account Discovery"),
        "T1069.002": ("Discovery", "Domain Groups Discovery"),
        "T1135": ("Discovery", "Network Share Discovery"),
        "T1021.001": ("Lateral Movement", "Remote Desktop Protocol"),
        "T1021.002": ("Lateral Movement", "SMB/Windows Admin Shares"),
        "T1021.003": ("Lateral Movement", "Distributed Component Object Model"),
        "T1021.006": ("Lateral Movement", "Windows Remote Management"),
        "T1570": ("Lateral Movement", "Lateral Tool Transfer"),
        "T1003": ("Credential Access", "OS Credential Dumping"),
        "T1003.006": ("Credential Access", "DCSync"),
        "T1039": ("Collection", "Data from Network Shared Drive"),
        "T1567": ("Exfiltration", "Exfiltration Over Web Service"),
        "T1567.002": ("Exfiltration", "Exfiltration to Cloud Storage"),
        "T1560": ("Exfiltration", "Archive Collected Data"),
        "T1562.001": ("Defense Evasion", "Disable or Modify Tools"),
        "T1486": ("Impact", "Data Encrypted for Impact"),
        "T1078.002": ("Initial Access", "Valid Accounts: Domain Accounts"),
        "T1017": ("Lateral Movement", "Application Deployment Software"),
    }

    seen_techniques = set()
    for key in ["A", "B", "C", "D"]:
        finding = state.findings.get(key)
        if not finding or not finding.mitre:
            continue
        directive = INVESTIGATION_DIRECTIVES[key]
        for tid in finding.mitre:
            if tid in seen_techniques:
                continue
            seen_techniques.add(tid)
            tactic, name = mitre_map.get(tid, ("—", tid))
            # Build evidence summary from first sentence of finding
            evidence_summary = finding.summary.split(". ")[0]
            if len(evidence_summary) > 100:
                evidence_summary = evidence_summary[:97] + "..."
            lines.append(f"| {tactic} | {tid} | {name} | {evidence_summary} |")
    lines.append("")

    # ═══════════════════════════════════════════════════════════════════════════
    # METHODOLOGY AND GUARDRAILS
    # ═══════════════════════════════════════════════════════════════════════════
    # ═══════════════════════════════════════════════════════════════════════════
    # RECOMMENDATIONS
    # ═��═════════════════════════════════════════════════════════════════════════
    lines.append("## Recommendations")
    lines.append("")
    lines.append(_build_recommendations(state.findings))
    lines.append("")

    lines.append("## Methodology and Guardrails")
    lines.append("")
    lines.append(
        "This investigation was conducted by an orchestrated multi-agent AI system "
        "consisting of four phases:"
    )
    lines.append("")
    lines.append(
        "1. **Data Reduction Pipeline (Phases 1-4):** Suricata alert ingestion → "
        "Zeek JSON correlation filtered to IOC IPs → targeted PCAP selection by timestamp → "
        "deep tshark extraction (DNS/HTTP/TLS/SMB/RDP/TCP conversations) on selected PCAPs only."
    )
    lines.append(
        "2. **Evidence Database (Phase 5):** All extracted evidence loaded into a structured "
        "SQLite database with indexed tables for fast querying by agents."
    )
    lines.append(
        "3. **Orchestrated Worker Agents (Phase 6):** Four specialized AI agents independently "
        "investigated each forensic question using SQL queries against the evidence database. "
        "Each agent operates under strict guardrails: read-only SQL only, bounded iterations, "
        "and every claim must cite query results."
    )
    lines.append(
        "4. **Report Synthesis (Phases 7-8):** Timeline assembly from all evidence items, "
        "followed by automated report generation."
    )
    lines.append("")
    lines.append("### Guardrails")
    lines.append("")
    lines.append("- **Read-only SQL:** Agents can only execute SELECT queries — writes are structurally blocked")
    lines.append("- **No hallucination:** Every finding must cite actual query results with real IPs and timestamps")
    lines.append("- **Bounded iterations:** Workers get a maximum of 30 tool-calling rounds")
    lines.append("- **Evidence-linked conclusions:** Every evidence item cites its source table")
    lines.append("- **Confidence labels:** HIGH/MEDIUM/LOW with explicit limitations for each finding")
    lines.append("- **Read-only PCAPs:** Source PCAP files are never modified; tshark only reads")
    lines.append("- **Caching:** Expensive Zeek scan is cached in `ingest/`; subsequent runs reuse the cache")
    lines.append("")

    lines.append("### Cost and Efficiency")
    lines.append("")
    lines.append(
        "- The Zeek JSON (30+ GB) is streamed once via ripgrep (Aho-Corasick) and matched records are cached\n"
        "- tshark is invoked only on the targeted PCAP subset, not all files\n"
        "- TCP conversation statistics (`tshark -z conv,tcp`) are extracted for external IPs to capture actual byte volumes\n"
        "- Agent reasoning cost is bounded by the iteration limit per worker"
    )

    return "\n".join(lines)


def _build_recommendations(findings: Dict[str, Finding]) -> str:
    """Generate prioritized recommendations based on findings evidence."""
    recs: List[str] = []

    # Analyze what was found to tailor recommendations
    has_rdp_exposure = False
    has_exfil = False
    has_smb_lateral = False
    has_credential_theft = False
    has_backup_browsing = False
    has_defense_evasion = False
    has_admin_shares = False

    for key, finding in findings.items():
        summary_lower = finding.summary.lower() if finding.summary else ""
        for item in finding.evidence:
            desc_lower = (item.description or "").lower()
            all_text = summary_lower + " " + desc_lower
            if "rdp" in all_text and ("external" in all_text or "inbound" in all_text):
                has_rdp_exposure = True
            if "temp.sh" in all_text or "exfil" in all_text:
                has_exfil = True
            if "smb" in all_text and ("lateral" in all_text or "admin$" in all_text or "c$" in all_text):
                has_smb_lateral = True
            if "dcsync" in all_text or "drsgetncchanges" in all_text or "backupkey" in all_text or "dpapi" in all_text:
                has_credential_theft = True
            if "veeam" in all_text or "backup" in all_text:
                has_backup_browsing = True
            if "uninstall" in all_text or "disable" in all_text or "tamper" in all_text:
                has_defense_evasion = True
            if "admin$" in all_text or "c$" in all_text:
                has_admin_shares = True

    # Critical (48-72 hours)
    recs.append("### Critical — Immediate Action Required (48-72 Hours)")
    recs.append("")

    recs.append("| # | Recommendation | Business Risk | MITRE Mitigation |")
    recs.append("|---|---------------|---------------|-----------------|")

    recs.append(
        "| C1 | **Immediate Credential Reset and Session Invalidation** — "
        "Reset all active domain user passwords in waves (Tier 0 admins first, then server admins, "
        "then all users). Invalidate all active VPN, RDP, SSO, and refresh-token sessions. "
        "Rotate service-account credentials. | If the attacker still holds working credentials or tokens, "
        "they may return even after containment. | M1018, M1027 |"
    )

    if has_rdp_exposure:
        recs.append(
            "| C2 | **Remove Direct RDP Exposure from the Internet** — "
            "Remove all internet NAT/port-forwarding rules to 3389/tcp. Block inbound RDP at the perimeter firewall. "
            "If RDP is needed, require access only through a hardened VPN with MFA, an RD Gateway, or a PAM/jump-host platform. "
            "| A directly exposed RDP service gives threat actors a standing doorway into the business and materially increases ransomware risk. | M1035 |"
        )

    if has_exfil:
        recs.append(
            "| C3 | **Block Known File-Sharing and Exfiltration Services at the Perimeter** — "
            "Implement DNS-layer and proxy-layer blocking of known file-sharing services (temp.sh, transfer.sh, file.io, mega.nz, etc.). "
            "Deploy a web proxy or CASB with TLS inspection. Create firewall alerts for any internal host uploading >100 MB to a single external IP within 24 hours. "
            "| The attacker exfiltrated data to temp.sh without any perimeter controls blocking or alerting. | M1031, M1037 |"
        )

    if has_admin_shares:
        recs.append(
            "| C4 | **Restrict Administrative Share Access on Domain Controllers** — "
            "Disable default administrative shares (ADMIN$, C$) on all DCs and critical servers via GPO. "
            "Where admin share access is required, restrict it to designated PAWs through host-based firewall rules. "
            "Monitor for anomalous SMB connections to admin shares (Event ID 5140/5145). "
            "| Unrestricted ADMIN$ and C$ access allowed the attacker to validate write permissions across the network and pivot to DCs. | M1035, M1030 |"
        )

    recs.append("")

    # High Priority (1-2 weeks)
    recs.append("### High Priority — Short Term (1-2 Weeks)")
    recs.append("")
    recs.append("| # | Recommendation | Business Risk | MITRE Mitigation |")
    recs.append("|---|---------------|---------------|-----------------|")

    recs.append(
        "| H1 | **Segment the Remote Access Landing Zone from Core Systems** — "
        "Place all remote access termination points into a dedicated management zone. "
        "Deny SMB, RPC, WinRM, RDP, and backup protocols from that zone to DCs, hypervisors, and backup infrastructure. "
        "| Without segmentation, one compromised remote-access host can reach servers, DCs, and backups in minutes. | M1030 |"
    )

    recs.append(
        "| H2 | **Implement Privileged Access Management for Administrative Remote Access** — "
        "Separate admin identities from normal user identities. Adopt a tiered model: Tier 0 for domain/identity systems, "
        "Tier 1 for servers, Tier 2 for workstations. Vault privileged passwords and rotate automatically. "
        "| If standard accounts can RDP to servers directly, one stolen account can escalate into broad operational impact. | M1026 |"
    )

    if has_backup_browsing:
        recs.append(
            "| H3 | **Implement Offline and Immutable Backups** — "
            "Implement a 3-2-1 backup strategy with at least one copy stored offline or in immutable (WORM) format. "
            "Segregate backup infrastructure from the main network and protect with separate credentials. "
            "| Without secure backups, the organization faces prolonged downtime and increased likelihood of paying ransom. | M1053 |"
        )

    if has_smb_lateral:
        recs.append(
            "| H4 | **Enforce East-West Network Segmentation for SMB and RDP** — "
            "Implement microsegmentation or host-based firewall policies to restrict SMB (445/tcp) and RDP (3389/tcp) "
            "between workstations and between workstation/server segments. Only permit from authorized jump servers. "
            "| The attacker conducted unrestricted SMB scanning across the network and RDP port scanning from a single beachhead. | M1030, M1035 |"
        )

    if has_credential_theft:
        recs.append(
            "| H5 | **Limit SAMR and LSARPC Enumeration from Non-DC Hosts** — "
            "Apply the SAM-R remote access restriction GPO to limit SAMR queries to authorized admin accounts only. "
            "Configure Windows Firewall rules to block DCE/RPC traffic from workstation-tier hosts to DCs except for domain-join and authentication. "
            "| The threat actor performed extensive SAMR operations from a compromised workstation, mapping privileged groups and users across the entire AD forest. | M1026, M1030 |"
        )

    recs.append("")

    # Medium Priority (1-3 months)
    recs.append("### Medium Priority — Medium Term (1-3 Months)")
    recs.append("")
    recs.append("| # | Recommendation | Business Risk | MITRE Mitigation |")
    recs.append("|---|---------------|---------------|-----------------|")

    recs.append(
        "| M1 | **Deploy Minimum Viable Network and Authentication Monitoring** — "
        "Stand up Zeek and Suricata on a SPAN/TAP, Windows event forwarding from DCs, and a SIEM. "
        "Build detections for: external RDP attempts, successful remote logons outside business hours, "
        "scan-like behavior within 15 minutes of remote access, and DCSync replication requests from non-DC hosts. "
        "| Without monitoring, the organization may not detect another intrusion until systems are already impacted. | M1047 |"
    )

    recs.append(
        "| M2 | **Strengthen Credential Hygiene and External Credential Exposure Monitoring** — "
        "Enforce 16+ character passwords, block known-breached passwords, require enterprise password manager, "
        "and subscribe to credential leak monitoring for corporate email domains. "
        "| If employees reuse passwords or choose breached passwords, valid-account attacks will remain likely. | M1027 |"
    )

    if has_exfil:
        recs.append(
            "| M3 | **Deploy Network-Based DLP and Traffic Anomaly Detection** — "
            "Deploy network DLP sensors at egress points. Implement NetFlow or Zeek-based anomaly detection "
            "to flag unusual outbound data volumes. Alert on workstation-tier hosts initiating HTTPS connections "
            "with cumulative upload volume exceeding baseline thresholds. "
            "| The highly asymmetric traffic pattern to a single external IP went undetected. | M1057, M1031 |"
        )

    recs.append(
        "| M4 | **Enforce MFA on All Remote Access** — "
        "Require MFA on every remote access path: VPN, RD Gateway, RDP broker, OWA/webmail, admin portals. "
        "Use phishing-resistant MFA (FIDO2/WebAuthn hardware keys for admins, TOTP as minimum fallback). "
        "| If passwords are stolen again, an attacker can re-enter with little resistance and repeat the intrusion. | M1032 |"
    )

    recs.append(
        "| M5 | **Audit and Harden SYSVOL / GPO Replication Paths** — "
        "Inventory GPP files (Groups.xml, Registry.xml), restrict who can read SYSVOL, and alert on unusual "
        "SMB access to \\\\domain\\SYSVOL from non-admin workstations. "
        "| GPO XML files often contain recoverable passwords; this case showed broad access to policy shares. | M1047, M1030 |"
    )

    recs.append(
        "| M6 | **DNS Logging, Filtering, and Resolver Policy** — "
        "Log all internal resolver queries, sinkhole or block high-risk file-sharing domains at the resolver, "
        "and alert on rare QNAMEs (pastebin, temp.sh, transfer.sh) from server VLANs. "
        "| Exfiltration used public DNS without friction; resolver visibility would have surfaced staging earlier. | M1031, M1047 |"
    )

    recs.append("")

    # High — additional controls aligned with manual IR report
    recs.append("### Additional High-Priority Controls")
    recs.append("")
    recs.append("| # | Recommendation | Business Risk | MITRE Mitigation |")
    recs.append("|---|---------------|---------------|-----------------|")

    recs.append(
        "| H6 | **Restrict LSARPC and SAMR from Workstation Tiers** — "
        "Tighten firewall rules so only hardened admin hosts may initiate lsarpc/named-pipe traffic to DCs; "
        "pair with SAM-R remote access restriction GPO. "
        "| Broad LSARPC/SAMR access enabled rapid domain mapping from a single beachhead. | M1026, M1030 |"
    )

    recs.append(
        "| H7 | **Least-Privilege File Shares and Sensitive Data Zones** — "
        "Segment file servers holding PII, law-enforcement, and financial exports; require justification-based ACLs "
        "and monitor bulk read patterns. "
        "| The actor harvested high-value files across many shares without containment. | M1038, M1047 |"
    )

    recs.append("")

    # Long-term strategic (manual report L1–L4)
    recs.append("### Long-Term — Strategic Program (6-18 Months)")
    recs.append("")
    recs.append("| # | Recommendation | Business Risk | MITRE Mitigation |")
    recs.append("|---|---------------|---------------|-----------------|")

    recs.append(
        "| L1 | **Zero Trust Architecture for Remote Access and Data** — "
        "Move toward device trust, continuous validation, and micro-segmentation so a single VPN/RDP foothold "
        "cannot reach DCs, backups, and file servers by default. "
        "| Flat remote-access trust models collapse quickly once credentials leak. | M1030, M1047 |"
    )

    recs.append(
        "| L2 | **Tabletop Exercises for Ransomware / Double Extortion** — "
        "Run cross-functional tabletops covering detection, comms, legal, and recovery with realistic exfil scenarios. "
        "| Teams that have rehearsed decisions respond faster and reduce business downtime. | — |"
    )

    recs.append(
        "| L3 | **Security Awareness Focused on Data Handling** — "
        "Train staff on spotting unusual RDP prompts, reporting large uploads, and protecting sensitive exports. "
        "| Human reporting can shorten dwell time when technical controls miss novel exfil channels. | M1047 |"
    )

    recs.append(
        "| L4 | **Phishing-Resistant MFA Everywhere (Especially Tier 0/1)** — "
        "Expand MFA beyond remote access to privileged consoles, cloud admin portals, and VPN concentrators; "
        "prefer FIDO2 for administrators. "
        "| Stolen passwords were sufficient for lateral movement; MFA reduces repeatability. | M1032 |"
    )

    return "\n".join(recs)


def _extract_iocs(findings: Dict[str, Finding]) -> List[dict]:
    """Extract IOCs from all findings' evidence items."""
    import ipaddress
    iocs: List[dict] = []
    seen = set()

    _rfc1918 = [
        ipaddress.ip_network("10.0.0.0/8", strict=False),
        ipaddress.ip_network("172.16.0.0/12", strict=False),
        ipaddress.ip_network("192.168.0.0/16", strict=False),
    ]

    def _is_external(ip: str) -> bool:
        try:
            addr = ipaddress.ip_address(ip)
            return not any(addr in net for net in _rfc1918)
        except ValueError:
            return False

    def _is_internal(ip: str) -> bool:
        try:
            addr = ipaddress.ip_address(ip)
            return any(addr in net for net in _rfc1918)
        except ValueError:
            return False

    for key in ["A", "B", "C", "D"]:
        finding = findings.get(key)
        if not finding:
            continue
        directive = INVESTIGATION_DIRECTIVES.get(key, {})
        phase_name = directive.get("title", key)

        for item in finding.evidence:
            # External IPs
            for ip in [item.src_ip, item.dst_ip]:
                if ip and _is_external(ip) and ip not in seen:
                    seen.add(ip)
                    context = item.description[:80] if item.description else "—"
                    iocs.append({
                        "type": "IP Address",
                        "value": ip,
                        "context": context,
                        "phase": phase_name,
                        "first_seen": item.ts or "—",
                    })

            # Key internal hosts (patient zero, DCs, file servers, targets)
            for ip in [item.src_ip, item.dst_ip]:
                if ip and _is_internal(ip) and ip not in seen:
                    # Include internal IPs in significant contexts
                    desc_lower = (item.description or "").lower()
                    if any(kw in desc_lower for kw in [
                        "patient zero", "pivot", "domain controller", "dc",
                        "file server", "exfil", "beachhead", "deployment",
                        "kerberos", "backup", "veeam", "credential",
                        "dcsync", "drsgetncchanges", "backupkey",
                        "ransomware", "executable", "hfs.exe", "kkwlo",
                    ]):
                        seen.add(ip)
                        context = item.description[:80] if item.description else "—"
                        iocs.append({
                            "type": "Internal Host",
                            "value": ip,
                            "context": context,
                            "phase": phase_name,
                            "first_seen": item.ts or "—",
                        })

            # Domains from description
            desc = item.description or ""
            for domain_keyword in ["temp.sh", "file.io", "transfer.sh", "mega.nz"]:
                if domain_keyword in desc.lower() and domain_keyword not in seen:
                    seen.add(domain_keyword)
                    iocs.append({
                        "type": "Domain",
                        "value": domain_keyword,
                        "context": desc[:80],
                        "phase": phase_name,
                        "first_seen": item.ts or "—",
                    })

            # Filenames from description
            for filename_keyword in [
                "hfs.exe", "kkwlo.exe", "Microsofts.exe", "delete.me",
                "HOW TO BACK FILES", "UninstallWinClient.exe",
                "hfs.ips.txt", "SETUP.EXE", "arrestees.zip", "incidents.zip",
                "user_db_export", "Groups.xml", "Registry.xml",
            ]:
                if filename_keyword in desc and filename_keyword not in seen:
                    seen.add(filename_keyword)
                    iocs.append({
                        "type": "Filename",
                        "value": filename_keyword,
                        "context": desc[:80],
                        "phase": phase_name,
                        "first_seen": item.ts or "—",
                    })

            # RDP cookies from description
            for cookie_keyword in ["lgallegos", "Administr", "WATER\\Adm", "WATER\\LGallegos", "jjjjjjjRD", "ecoborrow", "Springfi3"]:
                if cookie_keyword in desc and cookie_keyword not in seen:
                    seen.add(cookie_keyword)
                    iocs.append({
                        "type": "RDP Cookie / Username",
                        "value": cookie_keyword,
                        "context": desc[:80],
                        "phase": phase_name,
                        "first_seen": item.ts or "—",
                    })

    return iocs
